// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_botMessage from "./routes/api/botMessage.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.tsx";
import * as $api_prefill from "./routes/api/prefill.ts";
import * as $countdown from "./routes/countdown.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $greet_index from "./routes/greet/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $search from "./routes/search.tsx";
import * as $test_bots from "./routes/test/bots.tsx";
import * as $BotTest from "./islands/BotTest.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GroupOverview from "./islands/GroupOverview.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $NameInput from "./islands/NameInput.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/botMessage.ts": $api_botMessage,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.tsx": $api_login,
    "./routes/api/prefill.ts": $api_prefill,
    "./routes/countdown.tsx": $countdown,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/greet/index.tsx": $greet_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/search.tsx": $search,
    "./routes/test/bots.tsx": $test_bots,
  },
  islands: {
    "./islands/BotTest.tsx": $BotTest,
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Counter.tsx": $Counter,
    "./islands/GroupOverview.tsx": $GroupOverview,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/NameInput.tsx": $NameInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
