name: Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"

      # Deploy if on dev
      - name: Upload to Deno Deploy (dev)
        if: github.ref == 'refs/heads/dev'
        uses: denoland/deployctl@v1
        with:
          project: "dev-e91students"
          entrypoint: "./_fresh/server.js"
          root: ""
          exclude: .env

      # Deploy if on main
      - name: Upload to Deno Deploy (main)
        if: github.ref == 'refs/heads/main'
        uses: denoland/deployctl@v1
        with:
          project: "dev-e91students"
          entrypoint: "./_fresh/server.js"
          root: ""
          exclude: .env
